### ISSUE TITLE
Task Manager should check ID before adding to prevent task of same ID to be added

### ISSUE THREAD

**Issue by jasontanma** [cs2103jan2015-w14-4j/main#51]

**Comment by comilao** [comment]
I agree with it. This is important, I missed this part earlier. Thank you for adding it. May I ask how can I implement it? I could only think of using an Array, ArrayList or a BST(since it is faster) to hold all the existing IDs, each time there is a new ID, it will go through the existing IDs, if it is not found, that's the good news. @jasontanma
